[package]
name = "volta"
version = "0.1.0"
edition = "2021"
about = "Password Vault ğŸ” built with Rust that runs in the terminal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
clipboard = "0.5.0"
owo-colors = "3.5.0"
rand = "0.8.5"
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"
slug = "0.1.4"
tabled = "0.8.0"
unqlite = "1.5.0"

